/**
 * KaTeX stylesheet, inlined with its own fonts.
 * ------------------------------------------------------------------
 * Every PDF this app prints goes through Puppeteer's page.setContent()
 * + page.pdf(). setContent() gives the page no base URL, so a relative
 * stylesheet cannot resolve, and the document orchestrator used to pull
 * KaTeX's CSS with `@import url('https://cdn.jsdelivr.net/...')`.
 *
 * That was wrong twice over, and both faults print silently:
 *
 *  1. KaTeX draws U+2260 as a private-use slash glyph (U+E020) laid over
 *     an ordinary `=`. The slash exists only in KaTeX_Main-Regular. If
 *     that font has not arrived by the time page.pdf() runs, the slash
 *     draws nothing and the `=` stays -- so a paper that says "n != 0"
 *     prints "n = 0", reversing the condition. Nothing errors. This is
 *     not hypothetical: it reached a printed Grade 9 summative.
 *     page.setContent's `load` does not wait for web fonts (the `load`
 *     event covers stylesheets, not the faces they lazily fetch), so the
 *     CDN was always a race the renderer could lose.
 *
 *  2. The pinned CDN version was katex@0.16.9 while package.json installs
 *     ^0.16.45 -- markup generated by one version, positioned by another's
 *     stylesheet.
 *
 * Both go away by inlining: the CSS text and every woff2 face are read
 * from public/katex/ (already vendored from node_modules/katex/dist and
 * held byte-identical to it by lib/rubric-latex.vendor.test.ts) and
 * emitted as data: URIs. No network at render time, no font race, and
 * one version for markup and stylesheet alike.
 *
 * The .ttf and .woff fallbacks in KaTeX's own @font-face blocks are
 * dropped rather than inlined: they are not vendored, headless Chromium
 * reads woff2, and leaving them in would make the browser chase two
 * unresolvable relative URLs per face before reaching the data: URI.
 */

import fs from "node:fs";
import path from "node:path";

const VENDORED_DIR = path.join(process.cwd(), "public", "katex");
const STYLESHEET = path.join(VENDORED_DIR, "katex.min.css");
const FONT_DIR = path.join(VENDORED_DIR, "fonts");

/**
 * The pinned CDN stylesheet, used only if the vendored copy cannot be read.
 * Kept at the installed major.minor so a fallback render is at least styled
 * by the version that generated the markup -- unlike the 0.16.9 this
 * replaced. A fallback render still races the fonts, which is why
 * renderFormativeAssessmentPdfs also waits on document.fonts.ready.
 */
const CDN_FALLBACK = "https://cdn.jsdelivr.net/npm/katex@0.16.45/dist/katex.min.css";

/** Matches one `src: ...;` declaration inside an @font-face block. */
const SRC_DECLARATION = /src:([^;}]*)[;]?/g;
/** Matches a woff2 reference within such a declaration. */
const WOFF2_URL = /url\(fonts\/([A-Za-z0-9_-]+\.woff2)\)/;

function buildInlineCss(): string | null {
  let css: string;
  try {
    css = fs.readFileSync(STYLESHEET, "utf8");
  } catch {
    return null;
  }

  let missing = false;
  const inlined = css.replace(SRC_DECLARATION, (declaration) => {
    const match = WOFF2_URL.exec(declaration);
    if (!match) return declaration;

    let font: Buffer;
    try {
      font = fs.readFileSync(path.join(FONT_DIR, match[1]));
    } catch {
      missing = true;
      return declaration;
    }
    return `src:url(data:font/woff2;base64,${font.toString("base64")})format("woff2")`;
  });

  // All or nothing. A partially inlined stylesheet is the silent-failure
  // case again: the faces that resolved would draw and the rest would not.
  return missing ? null : inlined;
}

let cached: string | null | undefined;

/**
 * The full KaTeX stylesheet with every face embedded, or null when the
 * vendored assets are unreadable. Read once per process -- this is ~350KB
 * of base64 and every PDF render would otherwise pay for it again.
 */
export function katexInlineCss(): string | null {
  if (cached === undefined) cached = buildInlineCss();
  return cached;
}

/**
 * What a print stylesheet should open with: the inlined KaTeX CSS, or the
 * CDN @import if the vendored copy is missing. Callers concatenate this
 * ahead of their own rules.
 *
 * `@import` must come first in a stylesheet to have any effect, so the
 * fallback branch is only valid at the top of a <style> block. The inlined
 * branch carries no such constraint, but both are emitted in the same
 * position to keep one rule for callers.
 */
export function katexStylesheetBlock(): string {
  const inline = katexInlineCss();
  return inline ?? `@import url('${CDN_FALLBACK}');`;
}
