/**
 * A paper layout proposed from the class's marker boxes.
 *
 * A paper that was not generated by the platform -- a Standard Level paper
 * that arrived as a PDF, say -- has no stored master and so no layout unless
 * a teacher draws one region per part by hand (26 drags for Key Assessment
 * 1), which is why none had one. But every student sat the same printed
 * booklet, and the marker reports a box for every part of every student. Each
 * box on its own is a guess (+/- 0.08 of the page between students for the
 * same part on KA1); the class's MEDIAN is a far better estimate, and the
 * marker's PAGE agrees for every student on every part.
 *
 * So: one region per part, at the median top of the class's boxes, running
 * down to the next part's median top on the same page (the space between two
 * prompts belongs to the earlier part -- that is where its working goes), and
 * to the foot of the page for the last part on it. Full content width, since
 * the marker's x edges scatter and written papers stack their parts.
 *
 * This is a PROPOSAL. It is written to an UNLOCKED layout as source
 * 'marker_consensus' for the teacher to check in the editor, drag where it is
 * wrong, and lock; only a locked layout ever cuts a crop. The warnings say
 * where to look first: two parts whose medians are out of reading order (KA1:
 * 4(c) at 0.49 and Q5 at 0.43 on the same page), a part seen too few times,
 * a part the marker put on more than one page.
 *
 * Pure: takes observations, returns regions and warnings, touches nothing.
 */

import type { EvidenceBox } from "./evidence-crops";

/** Fewer observations than this and the median is one student's guess. */
export const CONSENSUS_MIN_OBSERVATIONS = 3;
/**
 * The least a next part's top may sit below this part's top for the two to be
 * in reading order. Two medians closer than this are the same place seen
 * twice, not a boundary; the part keeps its own median bottom and is flagged.
 */
export const CONSENSUS_MIN_GAP = 0.03;
/** The x extent: one content width for the whole paper, from the class's boxes. */
export const CONSENSUS_X_QUANTILES: [number, number] = [0.05, 0.95];
export const CONSENSUS_X_CLAMP: [number, number] = [0.02, 0.98];

export interface ConsensusObservation {
  questionNumber: number;
  partLabel: string | null;
  /** Position of the part in the paper, as assembleMarkScheme orders it. */
  sortOrder: number;
  /** Fractions of the page, page 1-indexed. */
  box: EvidenceBox;
  /**
   * 'reported' is the marker's own box; 'stored' is a padded, biased one
   * from before evidence_box_reported existed, whose top sits about PAD_FLOOR
   * above the raw top. Both are usable; the distinction is documentation.
   */
  kind: "reported" | "stored";
}

export interface ProposedRegion {
  questionNumber: number;
  partLabel: string | null;
  sortOrder: number;
  /** 0-indexed page of the reference PDF. */
  pageIndex: number;
  x0: number;
  y0: number;
  x1: number;
  y1: number;
  /** How many of the class's boxes, on the chosen page, this region rests on. */
  observations: number;
}

const clamp01 = (n: number) => Math.max(0, Math.min(1, n));

/**
 * The p-quantile of an ascending list by linear interpolation on p*(n-1) --
 * the median of [1, 2, 3, 4] is 2.5. Empty input is the caller's mistake and
 * returns NaN.
 */
export function quantile(sortedAscending: number[], p: number): number {
  const n = sortedAscending.length;
  if (n === 0) return Number.NaN;
  const pos = Math.max(0, Math.min(1, p)) * (n - 1);
  const lo = Math.floor(pos);
  const hi = Math.ceil(pos);
  const a = sortedAscending[lo];
  const b = sortedAscending[hi];
  return a + (b - a) * (pos - lo);
}

const median = (values: number[]) => quantile([...values].sort((p, q) => p - q), 0.5);

const partName = (questionNumber: number, partLabel: string | null) =>
  `Q${questionNumber}${partLabel ? `(${partLabel})` : ""}`;

interface PartGroup {
  key: string;
  questionNumber: number;
  partLabel: string | null;
  sortOrder: number;
  all: ConsensusObservation[];
  page: number;
  onPage: ConsensusObservation[];
}

export function proposeLayoutFromObservations(
  observations: ConsensusObservation[],
  pageCount: number
): { regions: ProposedRegion[]; warnings: string[] } {
  const warnings: string[] = [];

  // -- Group by part, and pick each part's page ----------------------------
  const groups = new Map<string, PartGroup>();
  for (const o of observations) {
    const key = `${o.questionNumber}|${o.partLabel ?? ""}`;
    let g = groups.get(key);
    if (!g) {
      g = { key, questionNumber: o.questionNumber, partLabel: o.partLabel, sortOrder: o.sortOrder, all: [], page: 0, onPage: [] };
      groups.set(key, g);
    }
    g.sortOrder = Math.min(g.sortOrder, o.sortOrder);
    g.all.push(o);
  }

  const kept: PartGroup[] = [];
  for (const g of groups.values()) {
    const name = partName(g.questionNumber, g.partLabel);
    const byPage = new Map<number, number>();
    for (const o of g.all) byPage.set(o.box.page, (byPage.get(o.box.page) ?? 0) + 1);
    // The mode; a tie goes to the lower page, and is worth a look either way.
    let page = 0;
    let best = -1;
    for (const [p, n] of byPage) {
      if (n > best || (n === best && p < page)) {
        page = p;
        best = n;
      }
    }
    if (byPage.size > 1) {
      const tied = [...byPage.values()].filter((n) => n === best).length > 1;
      if (tied) warnings.push(`${name}: the marker put it on ${byPage.size} different pages equally often; page ${page} was chosen. Check it.`);
      else if (g.all.length - best >= g.all.length / 3) {
        warnings.push(`${name}: the marker put it on page ${page} for most students but elsewhere for ${g.all.length - best} of ${g.all.length}. Check the page.`);
      }
    }
    if (page < 1 || page > pageCount) {
      warnings.push(`${name}: the marker's page (${page}) is outside this ${pageCount}-page paper, so no region was proposed.`);
      continue;
    }
    g.page = page;
    g.onPage = g.all.filter((o) => o.box.page === page);
    if (g.onPage.length < CONSENSUS_MIN_OBSERVATIONS) {
      warnings.push(`${name}: only ${g.onPage.length} of the class's boxes to go on, so its region is a rough guess. Check it.`);
    }
    kept.push(g);
  }

  // -- One content width for the paper -------------------------------------
  const allX0 = observations.map((o) => o.box.x0).sort((a, b) => a - b);
  const allX1 = observations.map((o) => o.box.x1).sort((a, b) => a - b);
  let x0 = clamp01(Math.max(CONSENSUS_X_CLAMP[0], quantile(allX0, CONSENSUS_X_QUANTILES[0])));
  let x1 = clamp01(Math.min(CONSENSUS_X_CLAMP[1], quantile(allX1, CONSENSUS_X_QUANTILES[1])));
  if (!(x1 > x0)) [x0, x1] = CONSENSUS_X_CLAMP;

  // -- Tops from the medians, bottoms from the next part on the page --------
  kept.sort((a, b) => a.sortOrder - b.sortOrder);
  const topOf = new Map(kept.map((g) => [g.key, median(g.onPage.map((o) => o.box.y0))]));

  const regions: ProposedRegion[] = [];
  for (const g of kept) {
    const name = partName(g.questionNumber, g.partLabel);
    const top = clamp01(topOf.get(g.key)!);
    const nextOnPage = kept
      .filter((h) => h !== g && h.page === g.page && h.sortOrder > g.sortOrder)
      .sort((a, b) => a.sortOrder - b.sortOrder)[0];

    let bottom: number;
    if (!nextOnPage) {
      bottom = 1;
    } else {
      const nextTop = clamp01(topOf.get(nextOnPage.key)!);
      if (nextTop >= top + CONSENSUS_MIN_GAP) {
        bottom = nextTop;
      } else {
        bottom = clamp01(median(g.onPage.map((o) => o.box.y1)));
        warnings.push(
          `${name} and ${partName(nextOnPage.questionNumber, nextOnPage.partLabel)} are out of reading order on page ${g.page} (the marker puts ${partName(nextOnPage.questionNumber, nextOnPage.partLabel)} at or above ${name}). ${name} was given its own median bottom; drag one of them to fix the order.`
        );
      }
    }

    if (!(bottom > top)) {
      warnings.push(`${name}: its boxes give an empty region, so none was proposed.`);
      continue;
    }
    regions.push({
      questionNumber: g.questionNumber,
      partLabel: g.partLabel,
      sortOrder: g.sortOrder,
      pageIndex: g.page - 1,
      x0,
      y0: top,
      x1,
      y1: bottom,
      observations: g.onPage.length,
    });
  }

  // Reading order, so expansion caps find the nearest region below each one.
  regions.sort((p, q) =>
    p.pageIndex !== q.pageIndex ? p.pageIndex - q.pageIndex : p.y0 - q.y0 || p.x0 - q.x0
  );
  return { regions, warnings };
}

/**
 * test_item_anchors.source for a region this module proposed. The propose
 * route overwrites only its own earlier proposals; a region with any other
 * source ('manual_draw', 'generated') is a teacher's decision or a
 * measurement, and is kept.
 */
export const MARKER_CONSENSUS_SOURCE = "marker_consensus";
