-- Persisted AI-generated nuanced analysis per student.
-- Generated by the StudentDashboard "Generate Analysis" button;
-- upserted on every (re)generation so only the latest is kept.
create table if not exists public.mastery_analyses (
  id          uuid primary key default gen_random_uuid(),
  student_id  uuid not null references public.profiles(id) on delete cascade,
  analysis_text text not null,
  generated_at  timestamptz not null default now(),
  unique (student_id)
);

-- RLS: students read their own; teachers read all.
alter table public.mastery_analyses enable row level security;

create policy "student_read_own" on public.mastery_analyses
  for select using (auth.uid() = student_id);

create policy "teacher_read_all" on public.mastery_analyses
  for select using (
    exists (
      select 1 from public.profiles
      where id = auth.uid() and role = 'teacher'
    )
  );

-- Only server-side service role writes (via API route).
create policy "service_upsert" on public.mastery_analyses
  for all using (true) with check (true);
