import type { Lesson, LessonSlide } from "./types";

/** Lesson 1.6 -- Describing Geometric Patterns.
 *
 *  Written against two worksheets: the "How Many Teams?" exploration (March
 *  Madness, 64 teams halving each round) with its Check Your Understanding
 *  page, and the four-page A1 Lesson 1.6 homework.
 *
 *  SHAPE: three acts, and the split is the point.
 *
 *    LEARN  -- one idea per slide, no worksheet question named. These are
 *              the prerequisites, front-loaded, so a student meets every
 *              tool before meeting any question.
 *    HINT   -- one slide per worksheet question, one nudge per part, and a
 *              pointer back to the learn slide that teaches it. A hint is a
 *              first move, never a method and never an answer.
 *    REVIEW -- after the work: what you should be able to do, the traps, how
 *              to write an explanation, the exit ticket.
 *
 *  The first version of this lesson put all three jobs on the same thirteen
 *  slides, so every slide carried body text, up to three worked examples, a
 *  check question and teacher notes at once. Separating the acts is what
 *  keeps a slide down to one idea; the test enforces the limits.
 *
 *  Two things this content is careful about, because a review caught both:
 *
 *  1. GROWING AND SHRINKING ARE SIGN-AWARE. "$0<r<1$ means decreasing" is
 *     false when the terms are negative: $-100, -60, -36$ climbs toward
 *     zero. That gets its own slide rather than a caveat on another one.
 *  2. THE PRIMER DOES NOT SOLVE THE EXPLORATION. No `primer` learn slide
 *     uses a knockout tournament or halves 64 of anything -- that is
 *     exploration Q1, Q2, Q4 and Q5. Hint slides name the context freely;
 *     by then the student is holding the worksheet.
 */

// ---- Act 1: learn. One idea each, at most one worked example.

const LEARN: LessonSlide[] = [
  {
    id: "terms-and-positions",
    act: "learn",
    title: "Terms and Positions",
    phase: "primer",
    minutes: 3,
    core: true,
    purpose: "The notation $a_n$, which every other slide leans on.",
    body: [
      "A sequence is a list of numbers in a set order.",
      "Each number is a TERM. Where it sits is its TERM NUMBER.",
      "$a_1$ is the first term, $a_2$ the second, $a_n$ the $n$th.",
      "So in $5, 8, 11, 14$ we have $a_1 = 5$ and $a_3 = 11$.",
      "The small number is a POSITION, not something you multiply by.",
    ],
    examples: [],
    table: null,
    plot: null,
    check: {
      question: "In $3, 6, 12, 24, 48$, what is $a_4$?",
      answer: "$a_4 = 24$. Count to the fourth number in the list.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote:
      "Say out loud once that $a_3$ is not $3a$. Fixing it here costs a sentence; fixing it at the nth-term slide costs the exponent too.",
    answers: ["Check: $a_4 = 24$."],
  },
  {
    id: "add-or-multiply",
    act: "learn",
    title: "Add, or Multiply?",
    phase: "primer",
    minutes: 3,
    core: true,
    purpose: "The two families. Everything else hangs off this distinction.",
    body: [
      "There are two ordinary ways to build a sequence.",
      "ADD the same number each step. That is ARITHMETIC.",
      "The number you add is the common difference, $d$.",
      "MULTIPLY by the same number each step. That is GEOMETRIC.",
      "The number you multiply by is the common ratio, $r$.",
    ],
    examples: [],
    table: null,
    plot: null,
    check: {
      question: "Is $2, 4, 8, 16$ built by adding or by multiplying?",
      answer: "Multiplying, by $2$ each time. So it is geometric with $r = 2$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Two words, two symbols. Put $d$ and $r$ on the board and leave them there all lesson.",
    answers: ["Check: multiplying, $r = 2$."],
  },
  {
    id: "finding-d",
    act: "learn",
    title: "Finding d",
    phase: "primer",
    minutes: 3,
    core: true,
    purpose: "The arithmetic test: subtract consecutive pairs.",
    body: [
      "To test for arithmetic, SUBTRACT each consecutive pair.",
      "Consecutive means sitting next to each other, nothing in between.",
      "Always later term minus earlier term.",
      "If every difference is the same, that number is $d$.",
    ],
    examples: [
      {
        title: "Example",
        steps: ["Take $5, 8, 11, 14$.", "$8 - 5 = 3$", "$11 - 8 = 3$", "$14 - 11 = 3$", "All the same."],
        answer: "Arithmetic, $d = 3$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "Find $d$ for $12, 7, 2, -3$.",
      answer: "$7 - 12 = -5$, $2 - 7 = -5$, $-3 - 2 = -5$. So $d = -5$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "The negative case is the one that slips: $-3 - 2$, not $2 - (-3)$. Later minus earlier, every time.",
    answers: ["Check: $d = -5$."],
  },
  {
    id: "finding-r",
    act: "learn",
    title: "Finding r",
    phase: "primer",
    minutes: 4,
    core: true,
    purpose: "The geometric test, and the direction of the division.",
    body: [
      "To test for geometric, DIVIDE each consecutive pair.",
      "Always LATER divided by EARLIER: $\\dfrac{a_2}{a_1}$, never $\\dfrac{a_1}{a_2}$.",
      "If every ratio is the same, that number is $r$.",
      "Self-check: if the sequence is shrinking, $r$ comes out less than $1$.",
      "If you got something bigger than $1$, you divided the wrong way round.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "Take $8, 12, 18, 27$.",
          "$\\dfrac{12}{8} = \\dfrac{3}{2}$",
          "$\\dfrac{18}{12} = \\dfrac{3}{2}$",
          "$\\dfrac{27}{18} = \\dfrac{3}{2}$",
        ],
        answer: "Geometric, $r = \\dfrac{3}{2}$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "Find $r$ for $100, 60, 36$.",
      answer:
        "$\\dfrac{60}{100} = \\dfrac{3}{5}$ and $\\dfrac{36}{60} = \\dfrac{3}{5}$. So $r = \\dfrac{3}{5}$, less than $1$, and the sequence is indeed shrinking.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote:
      "The reversed ratio is the commonest error on this topic. A student who writes $\\dfrac{100}{60}$ gets $\\dfrac{5}{3}$ and then calls a shrinking sequence a growing one.",
    answers: ["Check: $r = \\dfrac{3}{5}$."],
  },
  {
    id: "check-every-pair",
    act: "learn",
    title: "Check Every Pair",
    phase: "formalise",
    minutes: 3,
    core: true,
    purpose: "One matching pair proves nothing.",
    body: [
      "Test EVERY consecutive pair, not just the first one.",
      "Some sequences start out looking geometric and then stop following the pattern.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "Take $4, 8, 16, 48$.",
          "$\\dfrac{8}{4} = 2$",
          "$\\dfrac{16}{8} = 2$",
          "$\\dfrac{48}{16} = 3$",
          "The pattern broke at the last step.",
        ],
        answer: "Not geometric. Stopping after two pairs would have got this wrong.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "A student checks one pair of $3, 9, 27, 54$ and writes $r = 3$. Are they right?",
      answer: "No. $\\dfrac{54}{27} = 2$, not $3$, so the sequence is not geometric at all.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Insist on every ratio written down. A label with no arithmetic beside it earns nothing.",
    answers: ["Check: not geometric, the last ratio is $2$."],
  },
  {
    id: "neither-is-an-answer",
    act: "learn",
    title: "Neither Is a Real Answer",
    phase: "formalise",
    minutes: 3,
    core: false,
    purpose: "Legitimises a third outcome, and rules out zero terms.",
    body: [
      "If neither test gives a constant, the answer is NEITHER.",
      "That is a real answer, but you must show BOTH tests failing.",
      "Also: a geometric sequence never contains $0$.",
      "The first term and $r$ are both nonzero, so no term can ever be $0$.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "Take $1, 4, 9, 16$.",
          "Differences: $3, 5, 7$. Not constant, so not arithmetic.",
          "Ratios: $4$, $2.25$, $1.\\overline{7}$. Not constant, so not geometric.",
        ],
        answer: "Neither. Both tests had to be shown.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "Can $15, 0, 0, 0$ be geometric with $r = 0$?",
      answer: "No. A geometric sequence never contains $0$, because $r$ is never $0$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Showing only one test failing is the commonest lost mark on a neither question.",
    answers: ["Check: no, a geometric sequence never contains $0$."],
  },
  {
    id: "step-forward",
    act: "learn",
    title: "Getting the Next Term",
    phase: "primer",
    minutes: 3,
    core: true,
    purpose: "The recursive rule. Needed before students explore.",
    body: [
      "Once you know $r$, the next term is one multiplication.",
      "$a_{n+1} = a_n \\cdot r$",
      "$a_{n+1}$ means the term right after $a_n$: if $a_n$ is the 5th, $a_{n+1}$ is the 6th.",
      "The same FRACTION is applied every step, even when the amount changes.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "A ball dropped from $200$ cm bounces back to half its height each time.",
          "Half means $r = \\dfrac{1}{2}$.",
          "$200 \\cdot \\tfrac{1}{2} = 100$, then $50$, then $25$.",
          "Height LOST each bounce: $100$, then $50$, then $25$. Different every time.",
          "But the fraction lost is the same every bounce.",
        ],
        answer: "$200, 100, 50, 25$, geometric with $r = \\dfrac{1}{2}$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "A sequence starts at $81$ with $r = \\dfrac{1}{3}$. Write the next three terms.",
      answer: "$27$, then $9$, then $3$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote:
      "Do NOT swap this example for a knockout tournament. Same-number-or-same-fraction in that context IS exploration Q4 and Q5, and a primer that works it has answered the exploration in advance.",
    answers: ["Check: $27, 9, 3$."],
  },
  {
    id: "what-r-does-to-size",
    act: "learn",
    title: "What r Does to the Size",
    phase: "formalise",
    minutes: 4,
    core: false,
    purpose: "The size half of the growing question. The sign half is the next slide.",
    body: [
      "The SIZE of $r$ decides what happens to the size of the terms.",
      "Read $0 < r < 1$ as: $r$ is bigger than $0$ but smaller than $1$.",
    ],
    examples: [],
    table: {
      caption: "What $r$ does to the SIZE of the terms. Whether that counts as increasing is the next slide.",
      headers: ["Common ratio", "What happens to the terms"],
      rows: [
        ["$r > 1$", "move away from zero"],
        ["$r = 1$", "never change, like $7, 7, 7, 7$"],
        ["$0 < r < 1$", "move toward zero"],
        ["$r < 0$", "flip sign every step"],
      ],
    },
    plot: null,
    check: {
      question: "With $r = \\dfrac{4}{5}$, do the terms move toward zero or away from it?",
      answer: "Toward zero, because $\\dfrac{4}{5}$ is between $0$ and $1$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Keep this slide about SIZE only. Do not let the word decreasing in yet; that is the next slide's job.",
    answers: ["Check: toward zero."],
  },
  {
    id: "increasing-or-decreasing",
    act: "learn",
    title: "Increasing or Decreasing?",
    phase: "formalise",
    minutes: 5,
    core: true,
    purpose: "The sign half. The one thing on this topic most often taught wrongly.",
    body: [
      "Increasing means each term is BIGGER than the one before it.",
      "Compare the terms themselves, not how far they are from zero.",
      "So you need the sign of the terms AND the size of $r$. Both.",
      "Moving toward zero makes POSITIVE terms smaller, but NEGATIVE terms bigger.",
    ],
    examples: [
      {
        title: "Example - same r, opposite answers",
        steps: [
          "First term $100$, $r = \\dfrac{3}{5}$ gives $100, 60, 36$. Each term is smaller. DECREASING.",
          "First term $-100$, $r = \\dfrac{3}{5}$ gives $-100, -60, -36$.",
          "Is $-60$ bigger or smaller than $-100$? On a number line $-60$ is to the RIGHT.",
          "So each term is bigger. INCREASING.",
        ],
        answer: "Same $r$, opposite answers. The sign of the terms decided it.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "First term $-80$, $r = \\dfrac{1}{2}$. Increasing or decreasing?",
      answer: "$-80, -40, -20, -10$. The terms climb toward zero, so INCREASING.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote:
      "If a student answers decreasing, put $-80$ and $-40$ on a number line and ask which is further right. Note also $-3, -12, -48$: $r = 4$ is large, and the sequence DECREASES.",
    answers: ["Check: increasing."],
  },
  {
    id: "percent-into-r",
    act: "learn",
    title: "Turning Percent Words into r",
    phase: "formalise",
    minutes: 4,
    core: false,
    purpose: "Word problems describe $r$ rather than handing it over.",
    body: [
      "GROWS BY $10\\%$ means keep all of it and add a tenth: $r = 1 + 0.10 = 1.1$.",
      "FALLS BY $10\\%$ means keep nine tenths: $r = 1 - 0.10 = 0.9$.",
      "TWO-THIRDS OF THE PREVIOUS amount is already the multiplier: $r = \\dfrac{2}{3}$.",
      "Careful: growing by $10\\%$ is $r = 1.1$, NOT $r = 0.1$.",
      "Using $0.1$ would throw away nine tenths of what you had.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "An account has $3400$ followers and grows $10\\%$ a month. Find month 1.",
          "$r = 1.1$, so $3400 \\cdot 1.1 = 3740$.",
          "Check against the words: $10\\%$ of $3400$ is $340$, and $3400 + 340 = 3740$.",
        ],
        answer: "Month 1 is $3740$ followers.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "A price falls by $25\\%$ each year. What is $r$?",
      answer: "$r = 1 - 0.25 = 0.75$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "The add-it-back check in the example is worth doing every time; it catches $r = 0.1$ instantly.",
    answers: ["Check: $r = 0.75$."],
  },
  {
    id: "r-into-percent",
    act: "learn",
    title: "Turning r Back into a Percent",
    phase: "formalise",
    minutes: 3,
    core: false,
    purpose: "The reverse conversion, and the trap inside it.",
    body: [
      "The percent change is $(r - 1)$, written as a percent.",
      "$r = 1.1$ gives $(1.1 - 1) \\cdot 100\\% = +10\\%$.",
      "$r = 0.9$ gives $(0.9 - 1) \\cdot 100\\% = -10\\%$. The minus sign means a fall.",
      "Careful: $r = 0.9$ is NOT a $90\\%$ fall.",
      "The $90\\%$ is what is LEFT. The CHANGE is the $10\\%$ that went.",
    ],
    examples: [],
    table: null,
    plot: null,
    check: {
      question: "What percent change does $r = \\dfrac{2}{3}$ give?",
      answer: "$\\left(\\tfrac{2}{3} - 1\\right) \\cdot 100\\% \\approx -33.3\\%$, so about a $33.3\\%$ fall.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "The $90\\%$ misreading is the likeliest wrong answer on homework Q7(c). Name it out loud.",
    answers: ["Check: about a $33.3\\%$ fall."],
  },
  {
    id: "filling-a-table",
    act: "learn",
    title: "Filling a Table of Terms",
    phase: "formalise",
    minutes: 4,
    core: false,
    purpose: "The off-by-one, which appears on three different questions.",
    body: [
      "Fill a table left to right, multiplying by $r$ each time.",
      "COUNT THE GAPS, NOT THE LABELS.",
      "Five columns have four gaps, so Month $0$ to Month $4$ is four multiplications.",
      "When a question says to round, keep the full value in your calculator.",
      "Round only the number you write down.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "A table runs from Round $1$ to Round $6$.",
          "That is six columns.",
          "The gaps are $1\\to2$, $2\\to3$, $3\\to4$, $4\\to5$, $5\\to6$.",
          "Five gaps.",
        ],
        answer: "Five multiplications, one fewer than the number of columns.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "How many multiplications from Month $0$ to Month $12$?",
      answer: "Twelve. There are thirteen columns and twelve gaps between them.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote:
      "Compute exact, round only when writing. A student who rounds at every step and lands on the same figures is also correct.",
    answers: ["Check: twelve."],
  },
  {
    id: "nth-term-geometric",
    act: "learn",
    title: "Jumping to Any Term",
    phase: "formalise",
    minutes: 5,
    core: true,
    purpose: "The geometric explicit rule. Listing is fine for the 4th term and useless for the 12th.",
    body: [
      "$a_n = a_1 \\cdot r^{\\,n-1}$",
      "The exponent is $n-1$, not $n$: reaching the $n$th term takes $n-1$ steps.",
      "Count the gaps, not the labels. Same rule as the table slide.",
      "On a calculator use the power key, $x^y$ or $\\wedge$.",
      "Work out the power FIRST, then multiply by the first term.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "First term $40$, $r = \\dfrac{1}{2}$. Find the 4th term.",
          "From the 1st to the 4th is $4 - 1 = 3$ steps.",
          "$a_4 = 40 \\cdot \\left(\\tfrac{1}{2}\\right)^{3}$",
          "$\\left(\\tfrac{1}{2}\\right)^{3} = \\tfrac{1}{8}$, so $40 \\cdot \\tfrac{1}{8} = 5$.",
          "Check by listing: $40, 20, 10, 5$.",
        ],
        answer: "$a_4 = 5$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "First term $3$, $r = 2$. Find the 6th term.",
      answer: "$a_6 = 3 \\cdot 2^{5} = 96$. Listing: $3, 6, 12, 24, 48, 96$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote:
      "Make checking by listing the habit on short sequences. $r^{n}$ instead of $r^{\\,n-1}$ is invisible otherwise. A student who computes $3400 \\cdot 1.1$ and then raises THAT to the 12th is out by a factor of over a thousand.",
    answers: ["Check: $a_6 = 96$."],
  },
  {
    id: "nth-term-arithmetic",
    act: "learn",
    title: "The Same Idea, Arithmetic",
    phase: "formalise",
    minutes: 3,
    core: false,
    purpose: "Needed too: homework Q6(a) asks you to decide which kind of sequence you are looking at.",
    body: [
      "$a_n = a_1 + (n-1)d$",
      "Same $n-1$, same reason: $n-1$ steps from the first term.",
      "Geometric multiplies by $r$ each step; arithmetic adds $d$ each step.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "First term $2$, $d = 3$. Find the 7th term.",
          "$7 - 1 = 6$ steps.",
          "$a_7 = 2 + 6 \\cdot 3 = 20$.",
          "Check by listing: $2, 5, 8, 11, 14, 17, 20$.",
        ],
        answer: "$a_7 = 20$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "First term $3$, $d = 4$. Find the 6th term.",
      answer: "$a_6 = 3 + 5 \\cdot 4 = 23$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Put the two formulas side by side once. The shared $n-1$ is the thing worth remembering.",
    answers: ["Check: $a_6 = 23$."],
  },
  {
    id: "backwards-to-r",
    act: "learn",
    title: "Two Terms That Are Not Neighbours",
    phase: "formalise",
    minutes: 5,
    core: false,
    purpose: "Recovering $r$ across a gap, and the second root.",
    body: [
      "If two known terms are not next to each other, dividing them does not give $r$.",
      "It gives $r$ multiplied by itself once per step between them.",
      "Count the steps first, then undo the power with a root.",
      "A square root has TWO answers, one positive and one negative.",
      "A count or a length cannot be negative, so context often picks one.",
      "With no context, both are correct and you write both.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "The 2nd term is $6$ and the 4th term is $150$.",
          "Steps between them: $4 - 2 = 2$.",
          "$6 \\cdot r^{2} = 150$, so $r^{2} = 25$.",
          "$r = 5$ or $r = -5$.",
          "Check: $6, 30, 150$ and $6, -30, 150$. Both land on $150$.",
        ],
        answer: "$r = 5$ or $r = -5$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "The 1st term is $2$ and the 3rd term is $18$. Find $r$.",
      answer: "$2 \\cdot r^{2} = 18$, so $r^{2} = 9$ and $r = 3$ or $r = -3$. Both $2, 6, 18$ and $2, -6, 18$ work.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Students almost always find only the positive root. Ask directly whether a negative value could also square to $25$.",
    answers: ["Check: $r = 3$ or $r = -3$."],
  },
  {
    id: "backwards-to-first-term",
    act: "learn",
    title: "Walking Back to the First Term",
    phase: "formalise",
    minutes: 4,
    core: false,
    purpose: "Reversing a geometric sequence.",
    body: [
      "To step backwards, DIVIDE by $r$ instead of multiplying.",
      "If you are not given $r$, find it first from two consecutive terms you do have.",
      "Then divide back one step at a time, counting the gaps.",
      "Always check by walking forwards again from your answer.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "The 4th term is $9$ and the 5th term is $27$. Find the 1st term.",
          "These two are consecutive, so $r = \\dfrac{27}{9} = 3$.",
          "From the 4th back to the 1st is $3$ steps, so divide by $3$ three times.",
          "$\\dfrac{9}{3} = 3$, then $\\dfrac{3}{3} = 1$, then $\\dfrac{1}{3}$.",
          "Check forwards: $\\tfrac{1}{3}, 1, 3, 9, 27$.",
        ],
        answer: "The 1st term is $\\dfrac{1}{3}$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "The 3rd term is $18$ and the 4th is $54$. Find the 1st term.",
      answer: "$r = 3$, so back two steps: $\\tfrac{18}{3} = 6$, then $\\tfrac{6}{3} = 2$. Check: $2, 6, 18, 54$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "A fractional first term unsettles some students. Say plainly that $\\tfrac{1}{3}$ is a perfectly ordinary first term.",
    answers: ["Check: the 1st term is $2$."],
  },
  {
    id: "plotting-a-sequence",
    act: "learn",
    title: "Putting a Sequence on a Grid",
    phase: "formalise",
    minutes: 3,
    core: false,
    purpose: "Which axis is which, and why the points are not joined.",
    body: [
      "TERM NUMBER goes across the bottom. TERM VALUE goes up the side.",
      "So $2, 6, 18$ gives the points $(1, 2)$, $(2, 6)$ and $(3, 18)$.",
      "Plot points only. Do not join them with a line.",
      "A sequence exists only at whole term numbers: there is no term $2.5$.",
    ],
    examples: [],
    table: null,
    plot: null,
    check: {
      question: "What point does the 4th term of $2, 6, 18, 54$ give?",
      answer: "$(4, 54)$. The term number is the across value, the term itself is the up value.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Getting the axes the wrong way round is common and silent. Check the first plotted point of every student.",
    answers: ["Check: $(4, 54)$."],
  },
  {
    id: "line-or-curve",
    act: "learn",
    title: "Line or Curve?",
    phase: "formalise",
    minutes: 4,
    core: false,
    purpose: "Reading the kind of sequence off a picture, with the conditions that make it true.",
    body: [
      "Arithmetic points lie on a STRAIGHT line: the same amount added each step across.",
      "When $r$ is positive and not equal to $1$, geometric points lie on a CURVE.",
      "If $r$ is negative the points jump above and below, so the shape tells you nothing.",
      "And $7, 7, 7, 7$ is a flat line but is BOTH arithmetic ($d = 0$) and geometric ($r = 1$).",
      "When the shape is unclear, go back to the ratios and the differences.",
    ],
    examples: [],
    table: null,
    plot: {
      caption:
        "Two sequences on the same axes. The geometric one, 1, 2, 4, 8, 16, bends upward; the arithmetic one, 2, 5, 8, 11, 14, stays on a straight line. They cross, which is why you read the shape and not the height.",
      xLabel: "Term Number",
      yLabel: "Term Value",
      xMax: 5,
      yMax: 16,
      yStep: 4,
      xStep: 1,
      series: [
        {
          label: "Geometric, r = 2",
          kind: "geometric",
          points: [
            [1, 1],
            [2, 2],
            [3, 4],
            [4, 8],
            [5, 16],
          ],
        },
        {
          label: "Arithmetic, d = 3",
          kind: "arithmetic",
          points: [
            [1, 2],
            [2, 5],
            [3, 8],
            [4, 11],
            [5, 14],
          ],
        },
      ],
    },
    check: {
      question: "Points at $(1, 3)$, $(2, 7)$, $(3, 11)$, $(4, 15)$. Which kind?",
      answer: "Differences $4, 4, 4$ are constant, so arithmetic with $d = 4$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "The shape is a shortcut, not a proof. A student who reads values off and tests them is always safe.",
    answers: ["Check: arithmetic, $d = 4$."],
  },
  {
    id: "choosing-a-scale",
    act: "learn",
    title: "Choosing a Scale",
    phase: "formalise",
    minutes: 3,
    core: false,
    purpose: "Plotting values that span a big range without running off the page.",
    body: [
      "Look at your BIGGEST value first.",
      "Then pick an interval that fits it on the grid you have.",
      "Too small an interval runs off the page; too big and the small values pile up.",
    ],
    examples: [
      {
        title: "Example",
        steps: [
          "You must plot values from $64$ down to $2$.",
          "In steps of $1$ the axis needs $64$ grid lines. Off the page.",
          "In steps of $10$ the axis stops at $70$, but $8$, $4$ and $2$ sit on top of each other.",
          "In steps of $8$ you get nine lines from $0$ to $64$.",
        ],
        answer: "Label the axis $0, 8, 16, 24, \\ldots, 64$.",
      },
    ],
    table: null,
    plot: null,
    check: {
      question: "You must plot values from $1000$ down to $700$ on about ten lines. What interval?",
      answer: "Steps of $100$ from $0$ to $1000$, or better, start the axis at $700$ and go up in $50$s.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Worth saying that an axis does not have to start at zero when every value is far from it.",
    answers: ["Check: steps of $100$, or $50$s starting from $700$."],
  },
];

// ---- Act 2: hints. One slide per worksheet question, one nudge per part.
//
// A hint is a first move. It never states r, never gives an answer, and
// always points back at the learn slide that does the teaching. The answers
// are on the slide too, but behind the teacher layer.

function hintSlide(
  id: string,
  source: NonNullable<LessonSlide["source"]>,
  questionRef: string,
  title: string,
  body: string[],
  hints: LessonSlide["hints"],
  answers: string[],
  teacherNote = "",
): LessonSlide {
  return {
    id,
    act: "hint",
    title,
    phase: "formalise",
    minutes: 1,
    core: false,
    purpose: `Hints for ${questionRef}.`,
    body,
    examples: [],
    table: null,
    plot: null,
    check: null,
    questionRef,
    source,
    hints,
    teacherNote,
    answers,
  };
}

const HINTS: LessonSlide[] = [
  hintSlide(
    "hint-exp-q1",
    "exploration",
    "Exploration Q1",
    "How many teams in round 2?",
    ["Every team plays one other team, and only winners go on."],
    [{ part: "", hint: "Pair the teams up and ask how many pairs there are. One team survives each pair.", backTo: "step-forward" }],
    ["$32$ teams."],
  ),
  hintSlide(
    "hint-exp-q2",
    "exploration",
    "Exploration Q2",
    "How many teams in round 3?",
    ["Do to round 2 exactly what you did to round 1."],
    [{ part: "", hint: "Apply the same rule again to your answer from Q1.", backTo: "step-forward" }],
    ["$16$ teams."],
  ),
  hintSlide(
    "hint-exp-q3",
    "exploration",
    "Exploration Q3",
    "How many rounds before the championship?",
    ["Fill the table first, then count."],
    [
      {
        part: "",
        hint: "Keep applying the rule until only $2$ teams are left. That round IS the championship game, so it is not one of the rounds before it.",
        backTo: "filling-a-table",
      },
    ],
    ["The championship is round $6$ (with $2$ teams), so $5$ rounds come before it."],
    "Expect an argument about whether the championship counts. The maths is settled; the disagreement is about the English, and is worth naming as such.",
  ),
  hintSlide(
    "hint-exp-q4",
    "exploration",
    "Exploration Q4",
    "Is the same number eliminated each round?",
    ["Work out how many teams LEAVE each round, not how many stay."],
    [
      {
        part: "",
        hint: "Write the number knocked out in round 1, then round 2, then round 3. Compare those three numbers.",
        backTo: "add-or-multiply",
      },
    ],
    ["No: $32$, then $16$, then $8$ are eliminated. Different every round."],
  ),
  hintSlide(
    "hint-exp-q5",
    "exploration",
    "Exploration Q5",
    "Describe how the number of teams changes",
    ["Q4 showed the AMOUNT changes. So what stays the same?"],
    [{ part: "", hint: "Try dividing each round's total by the one before it. Is that the same every time?", backTo: "finding-r" }],
    ["It halves each round: multiply by $\\tfrac{1}{2}$, so $r = \\tfrac{1}{2}$."],
  ),
  hintSlide(
    "hint-exp-q6",
    "exploration",
    "Exploration Q6",
    "Plot the points",
    ["Round number across, teams remaining up the side."],
    [{ part: "", hint: "Your biggest value is $64$, so choose the vertical interval before you plot anything.", backTo: "choosing-a-scale" }],
    ["Points $(1,64), (2,32), (3,16), (4,8), (5,4), (6,2)$, vertical axis in steps of $8$."],
  ),
  hintSlide(
    "hint-exp-q7",
    "exploration",
    "Exploration Q7",
    "What do you notice about the shape?",
    ["Look at whether a ruler would pass through all your points."],
    [{ part: "", hint: "Ask whether the points drop by the same amount each step, or by less and less.", backTo: "line-or-curve" }],
    ["A curve, falling steeply then flattening, not a straight line."],
  ),
  hintSlide(
    "hint-cyu-q1",
    "check-your-understanding",
    "Check Your Understanding Q1",
    "Arithmetic, geometric, or neither?",
    ["Run BOTH tests on each one, and write the numbers down."],
    [
      { part: "(a)", hint: "Subtract the pairs first. Then notice what one of the terms is, and what that rules out.", backTo: "neither-is-an-answer" },
      { part: "(b)", hint: "These are fractions with the same denominator. Dividing by a fraction means multiplying by its reciprocal.", backTo: "finding-r" },
      { part: "(c)", hint: "Neither test will work here. Show both failing before you write the answer.", backTo: "neither-is-an-answer" },
      { part: "(d)", hint: "There is a decimal in the list. Divide anyway, and check the last pair as well as the first.", backTo: "check-every-pair" },
    ],
    [
      "(a) Arithmetic, $d = -5$. Not geometric: the ratios differ, and it contains $0$.",
      "(c) Neither. Differences $3, 5, 7, 9, 11$; ratios $4, 2.25, 1.\\overline{7}$.",
      "(d) Geometric, $r = \\dfrac{3}{2}$.",
    ],
    "Part (b) could not be read reliably off the source PDF. Check it against the printed sheet before class.",
  ),
  hintSlide(
    "hint-cyu-q2",
    "check-your-understanding",
    "Check Your Understanding Q2",
    "Gramma Fletcher's cookies",
    ["She makes $243$ in week 1, then two-thirds of the previous week each time."],
    [
      { part: "(a)", hint: "Two-thirds of the previous amount IS the multiplier. Apply it once for week 2, and count the steps for week 4.", backTo: "percent-into-r" },
      { part: "(b)", hint: "Keep going week by week until you reach $32$, then read off the week number.", backTo: "filling-a-table" },
      { part: "(c)", hint: "Ask whether the SAME multiplier was used every week. That is the whole definition.", backTo: "add-or-multiply" },
    ],
    [
      "(a) Week 2 is $162$; week 4 is $72$.",
      "(b) Week $6$. The list runs $243, 162, 108, 72, 48, 32$.",
      "(c) Yes, geometric with $r = \\dfrac{2}{3}$, because the same multiplier is used every week.",
    ],
  ),
  hintSlide(
    "hint-hw-q1",
    "homework",
    "Homework Q1",
    "First term 40, ratio one half, find the 4th term",
    ["You could list four terms, or jump straight there."],
    [{ part: "", hint: "How many steps from the 1st term to the 4th? It is not four.", backTo: "nth-term-geometric" }],
    ["$a_4 = 40 \\cdot \\left(\\tfrac{1}{2}\\right)^{3} = 5$."],
  ),
  hintSlide(
    "hint-hw-q2",
    "homework",
    "Homework Q2",
    "Describe each sequence in words",
    ["Say what kind it is, what the multiplier or difference is, and which way it goes."],
    [
      { part: "(a)", hint: "The terms are negative. Find the ratio first, then decide direction by comparing the terms themselves.", backTo: "increasing-or-decreasing" },
      { part: "(b)", hint: "Try subtracting rather than dividing on this one.", backTo: "finding-d" },
    ],
    ["(a) Geometric, $r = 4$, DECREASING: the terms are negative and moving further below zero.", "(b) Arithmetic, $d = -5$."],
  ),
  hintSlide(
    "hint-hw-q3",
    "homework",
    "Homework Q3",
    "First term 100, ratio three fifths: increasing or decreasing?",
    ["Write two or three terms out before you answer."],
    [{ part: "", hint: "Check the sign of the terms as well as the size of $r$. Both matter.", backTo: "increasing-or-decreasing" }],
    ["Decreasing: the terms are positive and $r$ is between $0$ and $1$, so each term is closer to zero."],
  ),
  hintSlide(
    "hint-hw-q4",
    "homework",
    "Homework Q4",
    "Arithmetic, geometric or neither?",
    ["Run both tests and give $d$ or $r$ where there is one."],
    [
      { part: "(a)", hint: "Subtract the pairs.", backTo: "finding-d" },
      { part: "(b)", hint: "Divide the pairs, later over earlier.", backTo: "finding-r" },
    ],
    ["(a) Arithmetic, $d = 3$.", "(b) Geometric, $r = 2$."],
  ),
  hintSlide(
    "hint-hw-q5",
    "homework",
    "Homework Q5",
    "First two terms are 1 and 5: give a next term",
    ["This one asks you to BUILD a sequence, not to label one."],
    [
      { part: "(a)", hint: "Work out the difference between $1$ and $5$, then add it again.", backTo: "finding-d" },
      { part: "(b)", hint: "Work out the ratio of $1$ to $5$, then multiply again.", backTo: "finding-r" },
      { part: "(c)", hint: "Pick anything that is not your answer to (a) and not your answer to (b). Then prove BOTH tests fail.", backTo: "neither-is-an-answer" },
    ],
    ["(a) $d = 4$, so $9$.", "(b) $r = 5$, so $25$.", "(c) Anything except $9$ and $25$, with both tests shown failing."],
    "The commonest lost mark on (c) is showing only one test failing.",
  ),
  hintSlide(
    "hint-hw-q6",
    "homework",
    "Homework Q6",
    "A sequence shown on a graph",
    ["Read the four values off the grid and write them down as a list first."],
    [
      { part: "(a)", hint: "Test your list both ways. Do not decide from the shape alone.", backTo: "line-or-curve" },
      { part: "(b)", hint: "Use whichever rule part (a) settled on. The graph stops at term 5, so you cannot read the 7th off it.", backTo: "nth-term-geometric" },
    ],
    ["Depends on the printed grid: read the four coordinates aloud before students start."],
    "The plotted coordinates are not legible in the digital copy. If the sequence turns out arithmetic, (b) needs $a_n = a_1 + (n-1)d$ instead.",
  ),
  hintSlide(
    "hint-hw-q7",
    "homework",
    "Homework Q7",
    "Deer population, first term 1000, ratio nine tenths",
    ["The table is in DECADES, not years."],
    [
      { part: "(a)", hint: "Positive terms, and $r$ between $0$ and $1$. Which way does that go?", backTo: "increasing-or-decreasing" },
      { part: "(b)", hint: "Multiply along the row, one decade at a time.", backTo: "filling-a-table" },
      { part: "(c)", hint: "Subtract $1$ from $r$ and write the result as a percent. Watch the sign.", backTo: "r-into-percent" },
    ],
    ["(a) Declining.", "(b) $1000, 900, 810, 729$.", "(c) $-10\\%$ per DECADE."],
    "The question says per year but the table is per decade. The intended answer is $-10\\%$ per decade. If a student presses, the honest per-year figure is $0.9^{1/10} \\approx 0.9895$, about $-1.05\\%$ a year, which is beyond this course. Noticing it earns full credit.",
  ),
  hintSlide(
    "hint-hw-q8",
    "homework",
    "Homework Q8",
    "4th term is 9, 5th term is 27: find the 1st",
    ["You are given two terms that ARE next to each other."],
    [{ part: "", hint: "Find $r$ from those two first. Then go backwards, and count how many steps back you need.", backTo: "backwards-to-first-term" }],
    ["$r = 3$, then back three steps: $3, 1, \\tfrac{1}{3}$. The 1st term is $\\dfrac{1}{3}$."],
  ),
  hintSlide(
    "hint-hw-q9",
    "homework",
    "Homework Q9",
    "Gianna's followers, 3400 growing 10% a month",
    ["Turn the percent into a multiplier before you do anything else."],
    [
      { part: "(a)", hint: "Month $0$ is the start. Multiply along, and keep the full value in the calculator between steps.", backTo: "filling-a-table" },
      { part: "(b)", hint: "One year is $12$ months from Month $0$. Work out the power before multiplying by $3400$.", backTo: "nth-term-geometric" },
      { part: "(c)", hint: "Ask whether the same multiplier is used every month.", backTo: "add-or-multiply" },
    ],
    [
      "(a) $3400, 3740, 4114, 4525, 4978$.",
      "(b) $3400 \\cdot 1.1^{12} \\approx 10671$ followers.",
      "(c) Yes: a constant percent growth is a constant multiplier, so it is geometric with $r = 1.1$.",
    ],
  ),
  hintSlide(
    "hint-hw-q10",
    "homework",
    "Homework Q10",
    "2nd term is 6, 4th term is 150: find r",
    ["These two terms are NOT next to each other."],
    [
      {
        part: "",
        hint: "Count the steps between them. Dividing gives $r$ raised to that power, not $r$ itself. And a square root has two answers.",
        backTo: "backwards-to-r",
      },
    ],
    ["$r^{2} = 25$, so $r = 5$ or $r = -5$. Both $6, 30, 150$ and $6, -30, 150$ work."],
    "A bare $-5$ is correct and should be marked so.",
  ),
];

// ---- Act 3: review. After the work.

const REVIEW: LessonSlide[] = [
  {
    id: "review-can-you",
    act: "review",
    title: "Can You Do These Now?",
    phase: "formalise",
    minutes: 3,
    core: true,
    purpose: "A self-check against the learning targets.",
    body: [
      "Tick the ones you could do without looking anything up.",
      "Find $d$ by subtracting, and $r$ by dividing later over earlier.",
      "Decide arithmetic, geometric or neither, showing both tests.",
      "Jump to any term with $a_n = a_1 \\cdot r^{\\,n-1}$ or $a_n = a_1 + (n-1)d$.",
      "Say whether a sequence increases or decreases, using the SIGN and the size of $r$.",
      "Turn percent words into $r$, and $r$ back into a percent change.",
    ],
    examples: [],
    table: null,
    plot: null,
    check: null,
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Any box left unticked names the learn slide to go back to. The wording here matches those slide titles on purpose.",
    answers: [],
  },
  {
    id: "review-traps",
    act: "review",
    title: "The Four Traps",
    phase: "formalise",
    minutes: 3,
    core: true,
    purpose: "The errors that actually appear on paper.",
    body: [
      "1. Dividing the wrong way round. Always LATER over EARLIER.",
      "2. Checking only the first pair. Check them all.",
      "3. Saying a fraction $r$ always means decreasing. Not if the terms are negative.",
      "4. Using $r^{n}$ instead of $r^{\\,n-1}$. Count the gaps, not the labels.",
    ],
    examples: [],
    table: null,
    plot: null,
    check: {
      question: "A sequence shrinks, and a student says $r = \\dfrac{5}{3}$. What went wrong?",
      answer: "They divided earlier by later. A shrinking sequence must have $r$ less than $1$.",
    },
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Two more worth naming aloud: growing by $10\\%$ is $r = 1.1$ not $0.1$, and $r = 0.9$ is a $10\\%$ fall not a $90\\%$ one.",
    answers: ["Check: they divided earlier by later."],
  },
  {
    id: "review-saying-it",
    act: "review",
    title: "Writing the Explanation",
    phase: "formalise",
    minutes: 4,
    core: true,
    purpose: "Most marks on this homework are for the explanation, not the number.",
    body: [
      "The word explain earns nothing without a calculation on the page.",
      "To classify: It is ___ because the ___ between consecutive terms is always ___, and I checked every pair.",
      "To say neither: The differences are ___ and the ratios are ___, so neither is constant.",
      "To give direction: It is ___ because the terms are ___ and $r$ is ___.",
      "That last frame needs BOTH blanks filled, or the negative cases come out wrong.",
    ],
    examples: [
      {
        title: "Example",
        steps: ["Take $-3, -12, -48$.", "Ratios: $\\dfrac{-12}{-3} = 4$ and $\\dfrac{-48}{-12} = 4$."],
        answer:
          "It is geometric with $r = 4$. It is decreasing, because the terms are negative and $r$ is greater than $1$, so each term sits further below zero.",
      },
    ],
    table: null,
    plot: null,
    check: null,
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Show the rubric on the next slide BEFORE students write, not after.",
    answers: [],
  },
  {
    id: "review-exit-ticket",
    act: "review",
    title: "Exit Ticket",
    phase: "formalise",
    minutes: 5,
    core: true,
    purpose: "Three marks, and students see all three before they write.",
    body: [
      "Take the sequence $-2, -8, -32$.",
      "Say whether it is arithmetic, geometric or neither, and prove it with numbers.",
      "Then say whether it is increasing or decreasing, and why.",
      "Use the sentence frames from the last slide.",
    ],
    examples: [],
    table: {
      caption: "How it is marked, out of $3$.",
      headers: ["Mark", "For"],
      rows: [
        ["$1$", "the classification is correct, with $r$ or $d$ named"],
        ["$1$", "at least TWO ratios or differences written out on the page"],
        ["$1$", "the direction sentence names both the sign of the terms and the size of $r$"],
      ],
    },
    plot: null,
    check: null,
    questionRef: null,
    source: null,
    hints: [],
    teacherNote: "Hold the line on mark 2. A correct label with no arithmetic beside it is one mark, not three.",
    answers: ["Geometric, $r = 4$. Decreasing, because the terms are negative and $r > 1$."],
  },
  {
    id: "review-challenge",
    act: "review",
    title: "If You Finished Early",
    phase: "formalise",
    minutes: 5,
    core: false,
    purpose: "Two extensions, both picking up the lesson's own loose ends.",
    body: [
      "1. Homework Q10 has two answers, $r = 5$ and $r = -5$.",
      "Write out both sequences to the 5th term, plot both, and describe how the pictures differ.",
      "2. Homework Q7 drops the deer by $10\\%$ every DECADE.",
      "What single yearly multiplier, applied ten times, would give the same drop?",
    ],
    examples: [],
    table: null,
    plot: null,
    check: null,
    questionRef: null,
    source: null,
    hints: [],
    teacherNote:
      "With $r = 5$ the terms stay positive and curve steeply; with $r = -5$ they alternate above and below the axis while growing. The yearly multiplier is NOT ten lots of $-1\\%$.",
    answers: [
      "$r = -5$ gives $\\tfrac{-6}{5}, 6, -30, 150, -750$, alternating.",
      "Yearly multiplier $0.9^{1/10} \\approx 0.9895$, about $-1.05\\%$ a year.",
    ],
  },
];

export const lesson16: Lesson = {
  slug: "1-6-describing-geometric-patterns",
  code: "1.6",
  title: "Describing Geometric Patterns",
  courseLabel: "Algebra 1",
  bigIdea:
    "A geometric sequence is built by multiplying by the same number every step, so one number, the common ratio $r$, controls the whole pattern.",
  pacing:
    "The Learn act is the lesson. Slides 1 to 4 and 7 are the primer, safe before the exploration, and run about 16 minutes; take the rest in the debrief and on day two. The Hint act is not taught -- students open the slide for whichever question has stopped them. The Review act is the last ten minutes, and the exit ticket is on it.",
  materials: [
    "the How Many Teams? exploration and its Check Your Understanding page",
    "the A1 Lesson 1.6 homework, questions 1 to 10",
  ],
  prerequisites: [
    "Multiplying and dividing whole numbers, fractions and decimals",
    "Dividing a fraction by a fraction, by multiplying by the reciprocal",
    "Raising a fraction or a decimal to a power, for example $\\left(\\tfrac{1}{2}\\right)^{3}$ and $1.1^{4}$",
    "Using the power key on a calculator, written $x^y$ or $\\wedge$ on most models",
    "Multiplying a negative number by a positive one",
    "Subtracting a negative number, for example $-6-(-1)=-5$",
    "Dividing a negative number by a negative number, for example $\\tfrac{-12}{-3}=4$",
    "Finding a percent of a number, for example $10\\%$ of $3400$",
    "Reading a double inequality such as $0<r<1$",
    "Plotting points on a grid and choosing a scale for an axis",
  ],
  warmUp: [
    { question: "1. Work out $\\dfrac{2/3}{1/3}$.", answer: "Answer: $2$." },
    { question: "2. Work out $\\left(\\tfrac{1}{2}\\right)^{3}$.", answer: "Answer: $\\tfrac{1}{8}$." },
    { question: "3. Work out $-6-(-1)$.", answer: "Answer: $-5$." },
    { question: "4. Work out $\\dfrac{-12}{-3}$.", answer: "Answer: $4$." },
    { question: "5. Find $10\\%$ of $3400$.", answer: "Answer: $340$." },
  ],
  learningTargets: [
    "I can find $d$ by subtracting, and $r$ by dividing later over earlier.",
    "I can decide arithmetic, geometric or neither, and show both tests.",
    "I can jump to any term with $a_n = a_1 \\cdot r^{\\,n-1}$ or $a_n = a_1 + (n-1)d$.",
    "I can say whether a sequence increases or decreases, using the sign of the terms and the size of $r$.",
    "I can turn percent words into $r$, and $r$ back into a percent change.",
    "I can fill a table of terms without an off-by-one error.",
    "I can plot a sequence and tell an arithmetic picture from a geometric one.",
    "I can work backwards from two later terms to find $r$ or the first term.",
  ],
  vocabulary: [
    { term: "Term", definition: "One number in a sequence. Its position is the term number.", example: "In $5, 8, 11, 14$ the third term is $11$." },
    {
      term: "Consecutive",
      definition: "Sitting next to each other in the list, with nothing in between.",
      example: "In $2, 4, 8$ the consecutive pairs are $2$ and $4$, then $4$ and $8$.",
    },
    { term: "Arithmetic sequence", definition: "You ADD the same number every step. That number is $d$.", example: "$5, 8, 11, 14$ has $d = 3$." },
    {
      term: "Geometric sequence",
      definition: "You MULTIPLY by the same number every step. That number is $r$. No term is ever $0$.",
      example: "$2, 4, 8, 16$ has $r = 2$.",
    },
    {
      term: "Common ratio",
      definition: "The multiplier. Find it by dividing a term by the one before it, always later over earlier.",
      example: "In $100, 60, 36$ the common ratio is $\\dfrac{60}{100} = \\dfrac{3}{5}$.",
    },
    {
      term: "Reciprocal",
      definition: "A fraction turned upside down. Dividing by a fraction means multiplying by its reciprocal.",
      example: "$\\dfrac{3}{4} \\div \\dfrac{2}{5} = \\dfrac{3}{4} \\cdot \\dfrac{5}{2}$.",
    },
    { term: "Recursive rule", definition: "How to get the NEXT term from the one you have.", example: "$a_{n+1} = a_n \\cdot r$." },
    {
      term: "Explicit rule",
      definition: "How to jump straight to any term without listing the ones before it.",
      example: "$a_n = a_1 \\cdot r^{\\,n-1}$, or $a_n = a_1 + (n-1)d$.",
    },
    {
      term: "Increasing and decreasing",
      definition: "Increasing means each term is bigger than the last. Compare the terms, not their distance from zero.",
      example: "$-100, -60, -36$ is INCREASING.",
    },
    {
      term: "Percent change",
      definition: "How much a quantity grows or falls each step, as a percent of what it was.",
      example: "$r = 1.1$ is a $10\\%$ rise; $r = 0.9$ is a $10\\%$ fall.",
    },
  ],
  slides: [...LEARN, ...HINTS, ...REVIEW],
  misconceptions: [
    {
      misconception: "Dividing the wrong way round, so $r$ comes out upside down.",
      whyItHappens: "Divide to get $r$ is remembered, but which over which is not.",
      howToFixIt: "Always LATER divided by EARLIER. Self-check: a shrinking sequence must give $r$ less than $1$.",
    },
    {
      misconception: "Checking only the first pair of terms.",
      whyItHappens: "The first ratio works, so the label is written before the rest are tested.",
      howToFixIt: "$4, 8, 16, 48$ passes twice and fails on the third. Check every consecutive pair.",
    },
    {
      misconception: "Grows by $10\\%$, so $r = 0.1$.",
      whyItHappens: "The percent in the sentence is copied straight in as the multiplier.",
      howToFixIt: "Growing means you KEEP what you had and add to it, so $r = 1.1$.",
    },
    {
      misconception: "$r = 0.9$, so it fell by $90\\%$.",
      whyItHappens: "The $0.9$ is read as the change rather than as what is left.",
      howToFixIt: "The $90\\%$ survives. The change is $(0.9 - 1) \\cdot 100\\% = -10\\%$.",
    },
    {
      misconception: "A fraction ratio always means decreasing.",
      whyItHappens: "Every classroom example of $0<r<1$ happens to have positive terms.",
      howToFixIt: "$-100, -60, -36$ has $r = \\tfrac{3}{5}$ and is INCREASING. Check the sign first, every time.",
    },
    {
      misconception: "A big $r$ always means increasing.",
      whyItHappens: "Size and direction get treated as the same thing.",
      howToFixIt: "$-3, -12, -48$ has $r = 4$ and is DECREASING. Compare terms on a number line.",
    },
    {
      misconception: "The same AMOUNT is removed each step, so it must be arithmetic.",
      whyItHappens: "In a halving sequence something is clearly taken away each step.",
      howToFixIt: "From $200$ the amounts lost are $100$, $50$, $25$. It is the FRACTION that is constant.",
    },
    {
      misconception: "Using $r^{n}$ instead of $r^{\\,n-1}$.",
      whyItHappens: "The term number is copied into the exponent without thinking where counting starts.",
      howToFixIt: "Count the gaps, not the labels. Check a short case by listing.",
    },
    {
      misconception: "Counting column headings instead of the gaps between them.",
      whyItHappens: "Month $0$ to Month $12$ looks like $13$ things.",
      howToFixIt: "The number of multiplications is the number of GAPS. Five columns have four gaps.",
    },
    {
      misconception: "Geometric means a curve, so a straight line rules it out.",
      whyItHappens: "The shape rule is learned without its conditions.",
      howToFixIt: "It holds only for $r>0$ and $r \\ne 1$. $7, 7, 7, 7$ is a flat line and geometric with $r = 1$.",
    },
    {
      misconception: "$15, 0, 0, 0$ is geometric with $r = 0$.",
      whyItHappens: "Multiplying by zero does produce the next term.",
      howToFixIt: "The first term and $r$ are both nonzero by definition, so no term is ever $0$.",
    },
  ],
  exitTicket: {
    task: "Take the sequence $-2, -8, -32$. Say whether it is arithmetic, geometric or neither and prove it with numbers; then say whether it is increasing or decreasing and why.",
    rubric: [
      "The classification is correct, with $r$ or $d$ named.",
      "At least TWO ratios or differences are written out on the page.",
      "The direction sentence names BOTH the sign of the terms and the size of $r$.",
    ],
  },
  challenge: [
    {
      task: "Homework Q10 has two answers, $r = 5$ and $r = -5$. Write out both sequences to the 5th term, plot both, and describe how the pictures differ.",
      answer:
        "With $r = 5$: $\\tfrac{6}{5}, 6, 30, 150, 750$, all positive, curving steeply upward. With $r = -5$: $\\tfrac{-6}{5}, 6, -30, 150, -750$, alternating above and below the axis with the size growing each step.",
    },
    {
      task: "Homework Q7 drops the deer by $10\\%$ every DECADE. What single yearly multiplier, applied ten times, gives the same drop, and what percent change is that per year?",
      answer:
        "$0.9^{1/10} \\approx 0.9895$, about a $1.05\\%$ fall per year. Ten of those compound to $0.9$, which is why it is not simply $-1\\%$.",
    },
  ],
  openQuestions: [
    {
      item: "Check Your Understanding Q1(b) - the strip of fractions",
      whyUnresolved: "The numerators did not survive text extraction from the PDF, so the exact sequence could not be read. Nothing was invented in its place.",
      whatWasDone:
        "The hint for Q1(b) teaches the skill the item assesses - test a fraction sequence by ratio, dividing by the reciprocal - without asserting an answer. Read the printed item before class.",
    },
    {
      item: "Homework Q6 - the four plotted points",
      whyUnresolved: "The grid is an image; only the axis labels and their ranges came through, so the plotted coordinates are unknown.",
      whatWasDone:
        "Both explicit rules are taught, and the Q6 hint tells students to read the values off and test them rather than judging by shape. Read the four coordinates aloud so a student with a reprinted copy is not locked out.",
    },
    {
      item: "Homework Q7(c) - decade versus year",
      whyUnresolved: "The table is in decades but the question asks for the percent change from one YEAR to the next.",
      whatWasDone:
        "The Q7 hint slide carries both the intended answer and the honest literal one in its teacher note. Worth reprinting the question as from one decade to the next.",
    },
  ],
};
