ALTER TABLE public.nuanced_analyses
  ADD COLUMN IF NOT EXISTS latex_content text;

COMMENT ON COLUMN public.nuanced_analyses.latex_content IS 'Printable XeLaTeX source generated by the packet generator (app/api/generate-packet).';
;
