-- KA1 Unit 1 (Grade 9 Standard Level): four parts whose mark scheme demanded
-- more than the printed question asked. Corrected before any mark on this
-- paper was accepted, so no accepted mark changes and no student's recorded
-- result moves; the teacher re-runs Clev's Marks against the corrected rows.
--
-- Q9's stem is a transcription standing in for a figure the database cannot
-- hold, and it stated the ANSWER to part (a) ("each new figure adds 2 tiles
-- to the row and 1 tile to the column"). The scheme was written in those
-- nouns, and the grader applied them as the required form: of 15 students,
-- 12 described the growth correctly and 9 lost marks on vocabulary --
-- "adding one unit to the left, right and bottom every figure" scored 0
-- while "two on each side and one on the bottom" scored 2. The stem now
-- describes the three printed figures and nothing about how they grow.
--
-- Q9(c) asks how the rule relates to "your answer from part (a)"; its scheme
-- required a link to the official structure instead. Q7(d) asks whether the
-- expression works for all x, and for an explanation; its scheme also
-- required the condition under which it DOES work, which the question never
-- asks for, and the part averaged 0.13 of 2 marks.
--
-- Kept 1:1 with platform/lib/fixtures/g9-standard-ka1-unit1.ts, which this
-- SQL was generated from. See section 10 of the Standard Level marking
-- policy for the standing rule this paper broke.

update public.test_items set question_text = 'The 84 students in fifth grade are gathering in the auditorium. The teachers choose $x$ students to perform a skit, and then split the remaining students into equal groups of 5 for a project activity. Does your expression in part (c) yield a valid whole number of groups for all whole-number values of $x$? Explain.', markscheme_text = 'A full-mark response answers what was asked: NO, with mathematics behind it. Either route is complete on its own -- a counterexample worked through ($x = 5$ gives $79 \div 5 = 15.8$, not a whole number), or the general reason ($84 - x$ has to be a multiple of 5, and it is not for every whole-number $x$). The question asks whether the expression works for all $x$, and for an explanation; it does NOT ask for the condition under which it does work, so do not require one. 2 marks: one for the conclusion NO reached from mathematics rather than asserted, one for the supporting reason being correct and complete. A student who gives both a counterexample and the condition has answered more than was asked, and earns 2, not more. A bare "no" earns 0, and "no, because you never know what $x$ might be" earns 0 -- neither contains any mathematics. "No, it only works when $x$ is divisible by 5" earns 1: the conclusion is right and divisibility is the right idea, but the condition is on the wrong quantity.'
 where test_id = 'a1c0f4e2-9d00-4b7e-8c21-000000000001' and question_number = 7 and part_label = 'd';

update public.test_items set question_text = 'Look at the pattern made from arrangements of $1 \times 1$ square tiles. [Marker''s note, describing the figures PRINTED on the paper. The student read no such sentence, so none of its words are required in any answer: Figure 1 is a row of 3 tiles with 1 further tile meeting the row at its centre (4 tiles); Figure 2 is a row of 5 with a line of 2 (7 tiles); Figure 3 is a row of 7 with a line of 3 (10 tiles).] Describe how the visual pattern is changing. You may use colours or symbols to support your description.', markscheme_text = 'A full-mark response describes the change well enough that a reader could draw the next figure: 3 tiles are added each time, one at each of the three growing ends -- the two ends of the row, and the far end of the line meeting it. 2 marks: one for the amount (3 tiles per figure, or 2 on one part and 1 on the other), one for WHERE the new tiles go. The question asks only for a description, so mark the content and not the vocabulary: "one on the left, one on the right and one on the bottom", "two on each side and one below", "each arm grows by one" and "2 in the row, 1 in the column" are the same answer, and each earns both marks. Do not require the words "row" or "column", and do not require the orientation to match this note -- which way the line runs is what the student sees on the page, not a mathematical claim. A description giving only the total change ("it adds 3 each time"), with nothing about where, earns 1. An annotated sketch showing the added tiles counts as description.'
 where test_id = 'a1c0f4e2-9d00-4b7e-8c21-000000000001' and question_number = 9 and part_label = 'a';

update public.test_items set question_text = 'Look at the pattern made from arrangements of $1 \times 1$ square tiles. [Marker''s note, describing the figures PRINTED on the paper. The student read no such sentence, so none of its words are required in any answer: Figure 1 is a row of 3 tiles with 1 further tile meeting the row at its centre (4 tiles); Figure 2 is a row of 5 with a line of 2 (7 tiles); Figure 3 is a row of 7 with a line of 3 (10 tiles).] How many squares are in Figure 5? Explain how you know using your description from part (a). You may sketch on the grid.', markscheme_text = 'A full-mark response gives 16 squares, explained from the structure: Figure 3 has 10, so Figure 4 has 13 and Figure 5 has 16 (adding 3 each time), or from a row of 11 and a line of 5 meeting it. Answer: 16. Follow-through from a wrong but consistently applied description in part (a).'
 where test_id = 'a1c0f4e2-9d00-4b7e-8c21-000000000001' and question_number = 9 and part_label = 'b';

update public.test_items set question_text = 'Look at the pattern made from arrangements of $1 \times 1$ square tiles. [Marker''s note, describing the figures PRINTED on the paper. The student read no such sentence, so none of its words are required in any answer: Figure 1 is a row of 3 tiles with 1 further tile meeting the row at its centre (4 tiles); Figure 2 is a row of 5 with a line of 2 (7 tiles); Figure 3 is a row of 7 with a line of 3 (10 tiles).] Write an expression that would give the number of squares in Figure $n$. How does your explicit rule relate to your answer from part (a)?', markscheme_text = 'A full-mark response gives $3n + 1$ (accept equivalents such as $4 + 3(n - 1)$) AND relates it to the student''s OWN answer to part (a), which is what the question asks for. 2 marks: one for a correct expression, one for the link. The link earns its mark when the student says what the 3 counts -- the tiles added per figure, in whatever words their own (a) used ("the 3 is the 3 squares added each time"; "the common difference is 3, which is the 2 on the sides and the 1 below"). Naming what the $+1$ counts (the one tile that is there before any growth) is a fuller answer, but the question does not ask for the two parts separately, so do not withhold the mark for its absence. A correct expression with no reference to the pattern at all earns 1; "it relates because it works when I test Figure 3" is a verification rather than a link, and earns nothing for the link. Follow-through: a student whose (a) was wrong earns the link mark for relating the rule to what they themselves described.'
 where test_id = 'a1c0f4e2-9d00-4b7e-8c21-000000000001' and question_number = 9 and part_label = 'c';